// Central icon module — Phosphor Icons (https://phosphoricons.com) re-exported under the
// names used across the app. Swapping icon sets only touches this file.
export {
  SquaresFour as LayoutGrid,
  Buildings as Building2,
  CalendarBlank as CalendarDays,
  Briefcase,
  FileText,
  Receipt,
  ChartBar as BarChart3,
  SignOut as LogOut,
  CaretDown as ChevronDown,
  CaretRight as ChevronRight,
  Plus,
  X,
  Check,
  Envelope as Mail,
  Phone,
  User,
  UserCircle,
  UsersThree,
  TrendUp as TrendingUp,
  Wallet,
  Trash as Trash2,
  PencilSimple as Pencil,
  DownloadSimple as FileDown,
  ShareNetwork as Share,
  MagnifyingGlass as Search,
  Lock,
  ShieldCheck,
  Gauge,
  Clock,
  Hourglass,
  List as Menu,
} from '@phosphor-icons/react'
